### PR TITLE
[fix]fix deepspeed initialization issue in finetune examples

### PR DESCRIPTION
**Pull request by Gforky**
修复 finetune 文件夹中 lora 微调脚本中deepspeed 初始化问题，目前脚本如果使用 deepspeed 会遇到 scheduler 初始化问题。

### CODE REVIEW

**Review by zRzRzRzRzRzRzR — APPROVED** [review]

**Comment by spacegoing** [comment]
@Gforky 

Would u pls share ur dspd yaml / run script config?

With this PR merged, I got error:
```
[rank0]: Traceback (most recent call last):                                                                        
[rank0]:   File "/workspace/public/users/lichang93/mydocker/cogvx/host_folder/CogVideo/finetune/train_cogvideox_lora.py", line 1548, in <module>                                                                                       
[rank0]:     main(args)                                                                                            
[rank0]:   File "/workspace/public/users/lichang93/mydocker/cogvx/host_folder/CogVideo/finetune/train_cogvideox_lora.py", line 1242, in main                                                                                           
[rank0]:     transformer, optimizer, train_dataloader, lr_scheduler = accelerator.prepare(                         
[rank0]:   File "/root/mambaforge/lib/python3.10/site-packages/accelerate/accelerator.py", line 1323, in prepare                                                                                                                       
[rank0]:     result = self._prepare_deepspeed(*args)                                                                                                                                                                                   
[rank0]:   File "/root/mambaforge/lib/python3.10/site-packages/accelerate/accelerator.py", line 1727, in _prepare_deepspeed                                                                                                            
[rank0]:     raise ValueError(                                                                                     
[rank0]: ValueError: You cannot create a `DummyOptim` without specifying an optimizer in the config file.       
```

**Comment by OwalnutO** [comment]
Same error.

[rank0]: ValueError: You cannot create a `DummyOptim` without specifying an optimizer in the config file.

**Comment by spacegoing** [comment]
@zRzRzRzRzRzRzR @Gforky Yes I propose to reverse this PR.


`accelerator.state.deepspeed_plugin.deepspeed_config.get("optimizer", "none").lower() == "none"`

This condition is at best, a typo `==` should be `!=`

at worst, introduces a bug that according to `accelerator.py: prepare_deepspeed()`:

image

is doomed to be error prone

**Comment by Gforky** [comment]
> @zRzRzRzRzRzRzR @Gforky Yes I propose to reverse this PR.
> 
> `accelerator.state.deepspeed_plugin.deepspeed_config.get("optimizer", "none").lower() == "none"`
> 
> This condition is at best, a typo `==` should be `!=`
> 
> at worst, introduces a bug that according to `accelerator.py: prepare_deepspeed()`:
> 
> image
> is doomed to be error prone

sry for the mess, try to fix it with a new PR.

**Pull request merged**
